### ISSUE TITLE
freeze while typing in less files

### ISSUE THREAD

**Issue by mino182** [KamiKillertO/vscode-colorize#184]
Hi, I have problem with performance while typing anything in less files. When I start typing, CPU load grow and VSCode freeze for seconds...

My settings:
`"colorize.languages": [
        "css",
        "sass",
        "scss",
        "less",
    ],
    "colorize.colorized_variables": [
        "CSS",
        "LESS"
    ],
    "colorize.enable_search_variables": false,`

Problem occurs in version 0.8.3. Version 0.8.1 works OK...

VSCode: 1.30.1

Thanks.

EDIT: Now I realize, that version 0.8.1 doesn't update change in variables... So it is faster, but has problem. Maybe there could be added some delay while typing?

**Comment by KamiKillertO** [comment]
🤔 does this happen only with less ?

**Comment by mino182** [comment]
Yes. I try only css and less, and in css I have only color properties, no variables. I have less file with many variables with inherited values (like @a: #000; @b: @a;) ... and other less files, where variables are used (traditional scenario I think :) ) And when I start write something in any less file, cursor freeze after 2-4 chars for 2-3 seconds... When I disable colorize, it's not happen...

Thanks for your attention.

**Comment by mino182** [comment]
I would like to ask, colorize parse variables only in opened files, or it browse every files in directory/subdirectory? May be it is my pc performance issue, cos I have many files (which I don't need to parse)...

**Comment by pingshunhuang** [comment]
I can see this in all files that this extension is enabled in. It didn't really freeze my mac, but everything is just like slow-mo. I need to really stop and wait for the typed characters to catch up.

My mac is a bit old, it's a 2015 model. My windows beast at home doesn't have this issue, but well, it has 32G RAM, so I can't really tell...

**Comment by KamiKillertO** [comment]
@mino182 by default colorize open and parse all files, in the current workspace, matching the settings `colorize.languages`, `colorize.include` and `colorize.exclude` (this one exclude files ^^)  and extract variables. Since vscode 1.28.0 opening a file from an extension triggers events for the other extensions, linters for exemple, this is why vscode freeze at opening. I suggest you to update your settings to make sure colorize doesn't parse unecessary files. I'm working on a patch to solve this issue but it'll not be released soon ><

**Comment by KamiKillertO** [comment]
But I think I can solve the problem with less i the next days ^^

**Comment by mino182** [comment]
Thanks and please, colorize.include is for add extra files, or to parse only that files? I need to parse only 2 files, for variables, but have many other .less files. I can't exclude everything, it will be very helpful to have "use only this files" option...

**Comment by idahotallpaul** [comment]
Experiencing massive slowdown issues in scss files as well with some bonkers results. If I add lines above where some vars are being colored, I end up with a slowly changing rainbow of highlighting on variables down the page. 

![screen shot 2019-01-31 at 4 11 38 pm](https://user-images.githubusercontent.com/296811/52091873-1c6ec900-2573-11e9-9612-fbfc21cfee8d.png)

**Comment by KamiKillertO** [comment]
😵 I've never encountered this kind of thing 😵.
@mino182  @pingshunhuang @idahotallpaul  This morning, I've released a new version that definitively solve this issue #179 , your problem might be linked. Tell me if you're still having freezes after upgrading

**Comment by idahotallpaul** [comment]
Thanks for the reply. Still seeing the issue. The link is to a screen capture: 

https://www.dropbox.com/s/41keqcimyn6bnbk/Screen-Recording-2019-02-01-at-9.13.16-AM.gif?dl=0

Had a colleague install the plugin and test on the same file. She didn't see the lag and the weird coloring until she added `“colorize.colorized_variables”: [“LESS”, “SASS”],` to her settings. 

It's a pretty good sized file but one that's pretty common -- _variables.scss from bootstrap.

Thanks.

**Comment by KamiKillertO** [comment]
🤔 ok did the problem appear after updating the file many times ? Or immediately after changing the settings?

**Comment by KamiKillertO** [comment]
Okay, I've managed to reproduce your problem. I think, I know how to fix it

**Comment by mino182** [comment]
I also still have issue with "slow motion effect" while typing... And when type few lines of code, then hold ctrl+Z for undo, it freeze for 2-3 sec. and then I see color mismatch (text which shouldn't be colored is colored...), but not rainbow as @idahotallpaul  (I use LESS)

**Comment by matthewfarlymn** [comment]
I have this issue also. It becomes so slow I usually need to restart VS Code.

**Comment by KamiKillertO** [comment]
Hello it's almost done.
This is before
![before](https://user-images.githubusercontent.com/9579729/52491510-8f0d2380-2bc7-11e9-80e5-891d0bce6c0d.gif)
This is after
![after](https://user-images.githubusercontent.com/9579729/52491545-a6e4a780-2bc7-11e9-93e1-3cadfa0faf00.gif)

**Comment by idahotallpaul** [comment]
Sweet!

**Comment by KamiKillertO** [comment]
I've just released a new version with this new feature.
The new feature is not activated by default, to active the feature you need to set the setting `colorize.colorize_only_visible_beta` to true and reload vscode. The feature is still experimental please report any issue you might encounter

**Comment by matthewfarlymn** [comment]
Thanks @KamiKillertO!

**Comment by pingshunhuang** [comment]
It seems to work fine on my windows machine, but didn't really work (or buggy) on my Mac (not sure if it's OS related).

color variables that are initially out of the viewport either won't have color at all or flashes while scrolling up and down

![screen shot 2019-02-19 at 11 35 53 am](https://user-images.githubusercontent.com/32624534/52982515-92f83b80-343a-11e9-9f65-0da3300d8650.png)

**Comment by KamiKillertO** [comment]
Thanks for reporting 😄 , I've noticed this kind of issue too. I'll fix it 👍

**Comment by KamiKillertO** [comment]
@pingshunhuang I've released a new version. Everything should always be colorized.

**Comment by mino182** [comment]
Hi, for me is everything allright now. Thanks.
